### ISSUE TITLE
Latest PR Problems

### ISSUE THREAD

**Issue by mefaba** [mefaba/show-geforce-on-steam#11]
Extension is not working on wishlist page and game pages. The reason is that following command returns null  document.getElementById("appHubAppName");

@arcataroger

**Comment by arcataroger** [comment]
I fixed the wishlist in #12, but not sure about the game page. I'm not getting that error =/ Can you reliably reproduce it?

**Comment by mefaba** [comment]
I am looking into it

**Comment by mefaba** [comment]
Basically the following node does not have game id. We should select another element on game pages .document.getElementById("appHubAppName");

**Comment by mefaba** [comment]
I fixed this issue with lates [commit](https://github.com/mefaba/show-geforce-on-steam/commit/744b45158d1baadabee1874a8c384929872a1866) @arcataroger
